# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY src/Passeio.Api/Passeio.Api.csproj src/Passeio.Api/
COPY src/Passeio.Data/Passeio.Data.csproj src/Passeio.Data/
COPY src/Passeio.Negocio/Passeio.Negocio.csproj src/Passeio.Negocio/
RUN dotnet restore src/Passeio.Api/Passeio.Api.csproj

COPY src/Passeio.Api/ src/Passeio.Api/
COPY src/Passeio.Data/ src/Passeio.Data/
COPY src/Passeio.Negocio/ src/Passeio.Negocio/

WORKDIR /src/src/Passeio.Api
RUN dotnet publish -c Release -o /app/publish

# Etapa de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Passeio.Api.dll"]
